# docker-compose.yml
version: '3.8'

services:
  # 1. SERVICIO DE BASE DE DATOS MYSQL
  mysql_db:
    image: mysql/mysql-server:8.0
    container_name: mysql_taller_db
    environment:
      # Las credenciales de la DB deben coincidir con tu archivo db.js
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: users_db # DB temporal para inicializar
    ports:
      # Puerto para acceder a la DB desde tu máquina host (opcional)
      - "3306:3306"
    volumes:
      # Esto persiste los datos entre reinicios de contenedores
      - mysql_data:/var/lib/mysql
      # Script de inicialización que crea las 3 bases de datos reales
      - ./init/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - microservices-network
    restart: always

  # 2. MICROSERVICIO DE USUARIOS
  user-service:
    build:
      context: ./user-service
      dockerfile: Dockerfile
    container_name: user_service_cont
    ports:
      - "3001:3001"
    environment:
      # Pasa las credenciales de la DB como variables de entorno (Buena práctica)
      DB_USER: localhost
      DB_PASSWORD: 1234
    depends_on:
      - mysql_db # Asegura que la DB se levante primero
    networks:
      - microservices-network

  # 3. MICROSERVICIO DE PRODUCTOS
  product-service:
    build:
      context: ./product-service
      dockerfile: Dockerfile
    container_name: product_service_cont
    ports:
      - "3002:3002"
    environment:
      DB_USER: localhost
      DB_PASSWORD: 1234
    depends_on:
      - mysql_db
    networks:
      - microservices-network

  # 4. MICROSERVICIO DE ÓRDENES (AGGREGATOR)
  order-service:
    build:
      context: ./order-service
      dockerfile: Dockerfile
    container_name: order_service_cont
    ports:
      - "3003:3003"
    environment:
      DB_USER: localhost
      DB_PASSWORD: 1234
    depends_on:
      - mysql_db
      - user-service # Depende de todos los servicios que llama
      - product-service
    networks:
      - microservices-network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: frontend
    ports:
      # Mapeamos el puerto 80 del contenedor al puerto 8080 del host
      - "8080:80" 
    networks:
      - microservices-network
    depends_on:
      - order-service # Para asegurar que el backend esté listo
      
volumes:
  mysql_data:

networks:
  microservices-network:
    driver: bridge